-- Generated by scripts/hypr2lua.
-- Source: omarchy-gruvbox-theme/hyprland.conf

local activeBorderColor = "rgb(7daea3)"
local inactiveBorderColor = "rgba(3c3836cc)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = inactiveBorderColor,
    },
    border_size = 2,
  },
  decoration = {
    rounding = 6,
    shadow = {
      enabled = true,
      range = 8,
      render_power = 2,
      color = "rgba(1d2021cc)",
    },
    blur = {
      enabled = true,
      size = 4,
      passes = 2,
      brightness = 0.75,
      contrast = 0.80,
      special = false,
    },
  },
  group = {
    col = {
      border_active = activeBorderColor,
      border_inactive = inactiveBorderColor,
    },
    groupbar = {
      col = {
        active = "rgba(3c383680)",
        inactive = "rgba(28282840)",
      },
      text_color = "rgb(d4be98)",
      text_color_inactive = "rgba(928374aa)",
    },
  },
})
